sudo: false
language: android
jdk:
  - oraclejdk8
android:
  components:
  - tools # to get the new `repository-11.xml`
  - tools # to install Android SDK tools 25.1.x
  - platform-tools
  - build-tools-24.0.3
  - android-24
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-24
  - extra-android-support
  - add-on
  - extra
branches:
  only:
  - master
  - develop
  - /^release/.*$/
  - /^hotfix/.*$/
script: "./gradlew ciBuild"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  email: false
  slack:
    rooms:
      secure: OabbD3IIowBBDDsBtnyjlBgnU4y+28p9eB/5fv9UAq+F3MoCdF9SkhAEuHo1FA3Xs0dp3KJuHF2rRFebxtwpIuemS7jOLvwz5C5OKVBcMZixCPbyd0ZdmckvzEQnO/gnzwK3POFT8mfZLij9l5wQPE+iBrRden8J7pR4Mim+m/N1NVhepVT683XhTYV3cbCwfnOpaFhcgkVsvzp6MPb4V9PkiI+JK/j8EWjf6JZolu3PYkifNG4OLBCFUcoPziixZCssEKXI7vB3qBbVWZJUQbzt+raTxRq9wimwvNvHKD6LJB3dHew3sRo/ZzjAJ/KGQKY0+rpsshakDukvVdIli0Zlu4+1iM2oskyx4Qir/zYo9/HA32CnEIL4HaVfB/hVQ7gaBXHED3bk4XS6gbyYIO3IhyzZXcY6sQqZrQGnVed7EvJiTLMUsKt8PuuWVeaMgxn9aw13bw90Qc69pW6T228gMx4A6o5Lx5EeJQqO7GJiHdPaqG3IQJCeJ/AtcW4pYyPUeggPUHyU29d110LON5M7XTRxtNZA/J0WlT9uDVCqQ1j+FJABgtCWUfHGNfzWGYUzhOHk39Zcqs4jMbol685k3SuRCY5SW/xT8FNyOHZ0whpNzvA/EnGp/BJ08Jl3PYSJ1Qcl8um8He7Bysfz7gn+bltY6Ez7yLIWIYDM8gE=
after_failure: "cat /home/travis/build/door2door-io/mobile-analytics-android/lib/build/outputs/lint-results-debug.xml"